name: "Update demo projects"

on:
  push:
  release:
    types: [ released ]

jobs:
  update_default_project:
    name: "Update regular project"
    runs-on: ubuntu-latest

    steps:
      - name: "Send webhook to ralphjsmit/tall-install-demo repo"
        env:
          WEBHOOK_ACCESS_SECRET: ${{ secrets.WEBHOOK_ACCESS_SECRET }}
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ralphjsmit/tall-install-demo/dispatches \
          -d '{"event_type":"package_released"}' \
          -u $WEBHOOK_ACCESS_SECRET:x-oauth-basic